export const NOT_HAVE_ACCOUNT = "Еще нет аккаунта?"
export const HAVE_ACCOUNT = "Уже есть аккаунт?"
export const REGISTER = "Зарегестрироваться"
export const LOGIN = "Войти"
export const EMAIL = "Почта"
export const PASSWORD = "Пароль"
export const CONFIRM_PASSWORD = "Подтверждение пароля"
export const USERNAME = "Имя пользователя"
export const MUST_BE_USERNAME = "Введите имя пользователя!"
export const MUST_BE_EMAIL = "Введите почту!"
export const INVALID_EMAIL = "Неверный формат почты!"
export const MUST_BE_PASSWORD = "Введите пароль!"
export const PASSWORD_LESS_MIN = "Пароль должен быть минимум 8 символов."
export const PASSWORDS_NOT_MATCH = "Пароли не совпадают!"

